#!/usr/bin/env python3
"""Score a Claude Code session for friction and write a postmortem when it trips.

Reads a hook payload on stdin (Stop / SubagentStop), streams the transcript
JSONL, and scores the session against thresholds derived from real transcript
data rather than intuition. Observe-only: always exits 0, never blocks a turn.

Thresholds come from mining 16 sessions of a working repo. Where a number is
calibrated to observed behaviour rather than a first principle, the docstring
in the check says so. Recalibrate with --calibrate against your own corpus.
"""

from __future__ import annotations

import json
import os
import re
import sys
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

# Tools whose repetition is legitimate observation, not thrashing. Without this
# exclusion the repeat metric inverts and ranks healthy UI work as the worst
# offender: screenshot polling looks identical to a stuck loop.
OBSERVATION_TOOLS = {
    "screenshot", "wait", "scroll", "read_page", "get_page_text",
    "read_console_messages", "read_network_requests", "tabs_context",
    "computer", "TaskOutput", "TaskList", "TaskGet", "Monitor",
}

# Files that are append-by-design. Edit counts against these measure
# bookkeeping, not churn, so they are exempt from the repeat-edit check.
LEDGER_PATTERNS = (
    re.compile(r"BOARD\.md$"),
    re.compile(r"LOCKS\.md$"),
    re.compile(r"CHANGELOG"),
    re.compile(r"/brain/.*/boards/"),
    re.compile(r"TODO\.md$"),
    re.compile(r"MEMORY\.md$"),
)

VERIFY_CMD = re.compile(
    r"\b(pytest|npm (run )?test|yarn test|pnpm test|go test|cargo test|"
    r"vitest|jest|npm run build|cargo build|make test|tox|uv run pytest)\b"
)

TEST_PATH = re.compile(
    r"(^|/)(tests?|spec|__tests__)/|"
    r"(^|/)test_[^/]*\.py$|"
    r"[^/]*_test\.(py|go|ts|js|rb)$|"
    r"[^/]*\.(test|spec)\.(ts|tsx|js|jsx|mjs)$"
)

ERROR_MARKERS = (
    "is_error", "Traceback", "command not found", "SyntaxError",
    "FAILED", "AssertionError", "fatal:", "ERROR:", "error TS",
    "Cannot find module", "ModuleNotFoundError", "npm ERR!",
)

NUDGE = re.compile(
    r"^\s*(continue|continu[ae]r?|keep going|go on|proceed|sigue|"
    r"continue from where you left off|carry on)[\s.!]*$",
    re.IGNORECASE,
)

INTERRUPT_MARKER = "[Request interrupted by user"

# Content that arrives on a user-type line but is not the human speaking.
# Background-agent completions dominate this category in agent-heavy sessions:
# counting them as human input both inflates the turn count and — worse —
# resets the autonomy counter, hiding exactly the long unsupervised stretches
# the grind metric exists to catch.
NOT_HUMAN = (
    "<task-notification>",
    "<system-reminder>",
    "<command-name>",
    "<local-command-stdout>",
    "<local-command-caveat>",
    "<command-message>",
    "<command-args>",
    "Base directory for this skill:",
    "Caveat: The messages below were generated by the user while running",
)


@dataclass
class Check:
    key: str
    label: str
    value: float
    threshold: float
    tripped: bool
    detail: str = ""
    note: str = ""


@dataclass
class Session:
    """Accumulated signals for one transcript."""

    tool_calls: int = 0
    assistant_turns: int = 0
    human_turns: int = 0
    errors: int = 0
    interrupts: int = 0
    nudges: int = 0
    max_grind: int = 0
    cur_grind: int = 0
    max_err_streak: int = 0
    cur_err_streak: int = 0
    edits: Counter = field(default_factory=Counter)
    edit_order: list = field(default_factory=list)
    verify_run: str = ""
    verify_streak: int = 0
    max_verify_streak: int = 0
    worst_verify_cmd: str = ""
    repeats: int = 0
    test_edits: list = field(default_factory=list)
    recent: list = field(default_factory=list)
    first_ts: str = ""
    last_ts: str = ""
    rolling_results: list = field(default_factory=list)
    max_rolling_err: float = 0.0


def _blocks(msg):
    content = msg.get("content")
    return content if isinstance(content, list) else []


def _text_of(msg) -> str:
    out = []
    content = msg.get("content")
    if isinstance(content, str):
        out.append(content)
    for blk in _blocks(msg):
        if isinstance(blk, dict):
            if blk.get("type") == "text":
                out.append(blk.get("text", ""))
            elif blk.get("type") == "tool_result":
                c = blk.get("content")
                if isinstance(c, str):
                    out.append(c)
                elif isinstance(c, list):
                    out.extend(
                        b.get("text", "") for b in c
                        if isinstance(b, dict) and b.get("type") == "text"
                    )
    return "\n".join(out)


def _sig(name: str, inp) -> str:
    """Stable signature for a tool call, used to detect exact repeats."""
    if not isinstance(inp, dict):
        return f"{name}:{str(inp)[:120]}"
    for k in ("command", "file_path", "path", "pattern", "url", "query"):
        if k in inp:
            return f"{name}:{k}={str(inp[k])[:160]}"
    return f"{name}:{json.dumps(inp, sort_keys=True)[:160]}"


def _is_ledger(path: str) -> bool:
    return any(p.search(path) for p in LEDGER_PATTERNS)


def scan(path: Path) -> Session:
    s = Session()
    with path.open(errors="replace") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                ev = json.loads(line)
            except json.JSONDecodeError:
                continue

            ts = ev.get("timestamp", "")
            if ts:
                s.first_ts = s.first_ts or ts
                s.last_ts = ts

            etype = ev.get("type")
            msg = ev.get("message", {}) or {}

            if etype == "assistant":
                s.assistant_turns += 1
                for blk in _blocks(msg):
                    if not isinstance(blk, dict) or blk.get("type") != "tool_use":
                        continue
                    name = blk.get("name", "?")
                    inp = blk.get("input", {})
                    s.tool_calls += 1
                    s.cur_grind += 1
                    s.max_grind = max(s.max_grind, s.cur_grind)

                    if name not in OBSERVATION_TOOLS:
                        sig = _sig(name, inp)
                        # A repeat only counts inside a short window; the same
                        # command an hour later is normal, three times in ten
                        # calls is a loop.
                        if sig in s.recent:
                            s.repeats += 1
                        s.recent.append(sig)
                        del s.recent[:-10]

                    if name in ("Edit", "Write", "NotebookEdit"):
                        fp = str(inp.get("file_path", "?"))
                        if not _is_ledger(fp):
                            s.edits[fp] += 1
                            s.edit_order.append(fp)
                        if TEST_PATH.search(fp):
                            s.test_edits.append(fp)

                    if name == "Bash":
                        cmd = re.sub(r"\s+", " ", str(inp.get("command", ""))).strip()
                        if VERIFY_CMD.search(cmd):
                            # Only *consecutive* re-runs of the identical command
                            # count. Running the suite once per change across a
                            # long session is healthy; running the same command
                            # five times in a row without it going green is the
                            # grind this metric is for. The streak is broken by a
                            # pass (see the tool_result branch) or a different
                            # verify command.
                            key = cmd[:120]
                            if key == s.verify_run:
                                s.verify_streak += 1
                            else:
                                s.verify_run, s.verify_streak = key, 1
                            if s.verify_streak > s.max_verify_streak:
                                s.max_verify_streak = s.verify_streak
                                s.worst_verify_cmd = key

            elif etype == "user":
                text = _text_of(msg)
                is_result = any(
                    isinstance(b, dict) and b.get("type") == "tool_result"
                    for b in _blocks(msg)
                )
                if INTERRUPT_MARKER in text:
                    s.interrupts += 1
                    s.cur_grind = 0
                    continue
                if is_result:
                    bad = any(mk in text for mk in ERROR_MARKERS) or any(
                        isinstance(b, dict) and b.get("is_error")
                        for b in _blocks(msg)
                    )
                    s.rolling_results.append(1 if bad else 0)
                    window = s.rolling_results[-30:]
                    if len(window) >= 10:
                        s.max_rolling_err = max(
                            s.max_rolling_err, sum(window) / len(window)
                        )
                    if bad:
                        s.errors += 1
                        s.cur_err_streak += 1
                        s.max_err_streak = max(s.max_err_streak, s.cur_err_streak)
                    else:
                        s.cur_err_streak = 0
                        # A clean result means the last verify command passed,
                        # so the re-run streak is not a loop.
                        s.verify_run, s.verify_streak = "", 0
                    continue

                stripped = text.strip()
                if not stripped:
                    continue
                # Machine-generated content on a user line is not supervision.
                if any(mk in stripped for mk in NOT_HUMAN):
                    continue
                # A genuine human turn resets the autonomy counter.
                s.human_turns += 1
                s.cur_grind = 0
                if NUDGE.match(stripped):
                    s.nudges += 1
    return s


def revisits(order: list) -> int:
    """Count returns to a file after editing a different one — ping-pong."""
    seen, last, n = set(), None, 0
    for f in order:
        if f != last and f in seen:
            n += 1
        seen.add(f)
        last = f
    return n


def evaluate(s: Session) -> list[Check]:
    top_edit = s.edits.most_common(1)
    rv = revisits(s.edit_order)

    return [
        Check(
            "grind", "Autonomous tool calls without human input",
            s.max_grind, 100, s.max_grind >= 100,
            f"longest unsupervised stretch: {s.max_grind} calls",
            "calibrated to observed operator tolerance, not a universal constant",
        ),
        Check(
            "repeat_edit", "Same file edited repeatedly",
            top_edit[0][1] if top_edit else 0, 15,
            bool(top_edit) and top_edit[0][1] >= 15,
            f"{Path(top_edit[0][0]).name} x{top_edit[0][1]}" if top_edit else "",
            "ledger/board files exempt",
        ),
        Check(
            "revisit", "Edit ping-pong between files",
            rv, 25, rv >= 25, f"{rv} returns to a previously-edited file",
        ),
        Check(
            "err_rate", "Peak rolling error rate",
            round(s.max_rolling_err * 100, 1), 12,
            s.max_rolling_err >= 0.12,
            f"{s.max_rolling_err:.0%} of results errored in the worst 30-call window",
        ),
        Check(
            "err_streak", "Consecutive failing results",
            s.max_err_streak, 4, s.max_err_streak >= 4,
            f"{s.max_err_streak} in a row",
        ),
        Check(
            "verify_loop", "Same verify command re-run without passing",
            s.max_verify_streak, 5, s.max_verify_streak >= 5,
            f"`{s.worst_verify_cmd}` x{s.max_verify_streak} consecutively"
            if s.worst_verify_cmd else "",
            "consecutive identical runs with no green transition",
        ),
        Check(
            "interrupts", "User interrupted the agent",
            s.interrupts, 2, s.interrupts >= 2,
            f"{s.interrupts} interrupts",
            "highest-precision signal available: an explicit human 'not this'",
        ),
        Check(
            "nudges", "Bare 'continue' prompts",
            s.nudges, 3, s.nudges >= 3,
            f"{s.nudges} nudges — agent kept stalling short of the goal",
        ),
        Check(
            "test_edits", "Test files edited",
            len(s.test_edits), 1, len(s.test_edits) >= 1,
            f"{len(s.test_edits)} edits to {len(set(s.test_edits))} test file(s)",
            "not a defect by itself — review whether tests were weakened to pass",
        ),
    ]


def render(s: Session, checks: list[Check], sid: str) -> str:
    tripped = [c for c in checks if c.tripped]
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    per_turn = s.tool_calls / s.human_turns if s.human_turns else float(s.tool_calls)

    out = [
        f"# Session postmortem — {sid[:8]}",
        "",
        f"*Generated {now} · {len(tripped)} of {len(checks)} tripwires fired*",
        "",
        "## Shape",
        "",
        f"- {s.tool_calls} tool calls across {s.assistant_turns} assistant turns",
        f"- {s.human_turns} human turns ({per_turn:.0f} tool calls per human turn)",
        f"- {s.errors} errored results, {s.interrupts} interrupts",
        "",
    ]

    if tripped:
        out += ["## Tripped", ""]
        for c in tripped:
            out.append(f"### {c.label}")
            out.append("")
            out.append(f"**{c.value}** against a threshold of {c.threshold}. {c.detail}")
            if c.note:
                out.append("")
                out.append(f"*{c.note}*")
            out.append("")
    else:
        out += ["## Tripped", "", "Nothing. Session ran clean.", ""]

    passed = [c for c in checks if not c.tripped]
    if passed:
        out += ["## Within bounds", ""]
        out += [f"- {c.label}: {c.value} (limit {c.threshold})" for c in passed]
        out.append("")

    out += [
        "## What to do with this",
        "",
        "These are strain signals, not proof of failure. They were calibrated on a",
        "corpus where every session eventually succeeded, so treat a trip as a",
        "prompt to look, not a verdict.",
        "",
        "Ask, in order:",
        "",
        "1. Was the goal ever stated as something a machine could check?",
        "2. Did a check exist that the agent could run without asking a human?",
        "3. If tests were edited, were they made weaker or made correct?",
        "4. Which single missing signal would have caught this earliest?",
        "",
        "Answer 4, then build that check. That is the whole loop.",
        "",
    ]
    return "\n".join(out)


def main() -> int:
    raw = sys.stdin.read() if not sys.stdin.isatty() else "{}"
    try:
        payload = json.loads(raw or "{}")
    except json.JSONDecodeError:
        payload = {}

    # Explicit path wins, so the analyzer can be run over any transcript
    # offline for calibration.
    tpath = None
    for arg in sys.argv[1:]:
        if not arg.startswith("-"):
            tpath = arg
    tpath = tpath or payload.get("transcript_path")
    if not tpath or not Path(tpath).exists():
        return 0

    path = Path(tpath)
    sid = payload.get("session_id") or path.stem

    try:
        s = scan(path)
    except Exception as exc:  # never let analysis break the session
        print(f"session_health: scan failed: {exc}", file=sys.stderr)
        return 0

    # Too small to say anything meaningful about.
    if s.tool_calls < 20:
        return 0

    checks = evaluate(s)
    tripped = [c for c in checks if c.tripped]

    if "--stdout" in sys.argv:
        print(render(s, checks, sid))
        return 0

    if not tripped:
        return 0

    outdir = Path(
        os.environ.get("SHIP_POSTMORTEM_DIR")
        or Path(payload.get("cwd") or ".") / ".claude" / "postmortems"
    )
    try:
        outdir.mkdir(parents=True, exist_ok=True)
        stamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M")
        dest = outdir / f"{stamp}-{sid[:8]}.md"
        dest.write_text(render(s, checks, sid))
        # Surfaced to the user, not to the model: this is a report, not a
        # correction, and it must not steer the next turn.
        print(
            f"session-health: {len(tripped)} tripwire(s) fired "
            f"({', '.join(c.key for c in tripped)}) → {dest}",
            file=sys.stderr,
        )
    except Exception as exc:
        print(f"session_health: write failed: {exc}", file=sys.stderr)

    return 0


if __name__ == "__main__":
    sys.exit(main())
